# Generated by Django 3.1.7 on 2021-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=60, verbose_name='EMAIL ID')),
                ('username', models.CharField(max_length=30, verbose_name='USERNAME')),
                ('password', models.CharField(max_length=30, verbose_name='PASSWORD')),
                ('firstname', models.CharField(max_length=30, verbose_name='FIRST NAME')),
                ('lastname', models.CharField(max_length=30, verbose_name='LAST NAME')),
                ('mobile_no', models.IntegerField(verbose_name='MOBILE NO.:')),
            ],
        ),
    ]
