# Generated by Django 3.1.7 on 2021-03-24 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_covid_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tbl',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_tbl',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='USERNAME'),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_covid_api_app.user_tbl')),
            ],
        ),
    ]
