# Generated by Django 3.1.7 on 2021-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_covid_api_app', '0003_auto_20210325_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file_upload',
            field=models.FileField(upload_to=''),
        ),
    ]
