# Generated by Django 3.1.7 on 2021-03-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_covid_api_app', '0004_auto_20210325_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmenttype',
            old_name='app_type',
            new_name='appointment_type',
        ),
    ]
